# Generated by Django 5.1.1 on 2024-10-03 07:39

import anonym_form_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('name_dep', models.CharField(max_length=350, verbose_name='Наименование организации')),
            ],
            options={
                'verbose_name': 'город/организация',
                'verbose_name_plural': 'города/организации',
                'db_table': 'admin_panel_app_citydepmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommandNumberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_number', models.IntegerField(verbose_name='Номер отдела/Сокращение')),
                ('command_name', models.CharField(max_length=150, verbose_name='Наименование отдела')),
                ('show', models.BooleanField(default=True, verbose_name='Отображать отдел')),
            ],
            options={
                'verbose_name': 'номер отдела',
                'verbose_name_plural': 'номера отделов',
                'db_table': 'ToDo_tasks_commandnumbermodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('personnel_number', models.CharField(default=None, max_length=20, null=True, verbose_name='Табельный номер')),
                ('user_phone', models.IntegerField(blank=True, default=None, null=True, verbose_name='№ телефона внутренний')),
                ('right_to_sign', models.BooleanField(default=False, verbose_name='Право подписывать задания')),
                ('check_edit', models.BooleanField(default=True, verbose_name='Возможность редактирования задания')),
                ('can_make_task', models.BooleanField(default=True, verbose_name='Возможность выдавать задания')),
                ('cpe_flag', models.BooleanField(default=False, verbose_name='Флаг ГИП (техническая метка)')),
                ('mailing_list_check', models.BooleanField(default=True, verbose_name='Получать рассылку')),
                ('work_status', models.BooleanField(default=True, verbose_name='Сотрудник работает')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'db_table': 'ToDo_tasks_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GroupDepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_dep_abr', models.CharField(max_length=10, verbose_name='Сокращенное название управления')),
                ('group_dep_name', models.CharField(max_length=250, verbose_name='Полное название управления')),
                ('show', models.BooleanField(default=True, verbose_name='Отображать отдел')),
            ],
            options={
                'verbose_name': 'управление',
                'verbose_name_plural': 'управления',
                'db_table': 'ToDo_tasks_groupdepartmentmodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobTitleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'должность',
                'verbose_name_plural': 'должности',
                'db_table': 'ToDo_tasks_jobtitlemodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MoreDetailsEmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=anonym_form_app.models.upload_to, verbose_name='Файл')),
                ('outside_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Внешняя почта')),
                ('mobile_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Мобильный телефон')),
                ('date_birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
                ('room', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер комнаты')),
                ('date_birthday_show', models.BooleanField(default=False, null=True, verbose_name='Отображать день рождения')),
                ('send_email_salary_blank', models.BooleanField(default=False, verbose_name='Отсылать расчетный листок')),
            ],
            options={
                'verbose_name': 'дополнительная информация по сотруднику',
                'verbose_name_plural': 'дополнительная информация по сотрудникам',
                'db_table': 'admin_panel_app_moredetailsemployeemodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubdivisionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_answer', models.CharField(max_length=260, verbose_name='Ответственное подразделение')),
            ],
            options={
                'verbose_name': 'ответственное подразделение',
                'verbose_name_plural': 'ответственные подразделения',
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important_of_question', models.IntegerField(choices=[(1, 'Низкая'), (2, 'Средняя'), (3, 'Высокая')], default=2, verbose_name='Важность обращения')),
                ('type_of_question', models.IntegerField(choices=[(1, 'Жалоба'), (2, 'Предложение')], default=2, verbose_name='Тип обращения')),
                ('question', models.TextField(max_length=5100, verbose_name='Текст обращения')),
                ('date_add', models.DateField(auto_now_add=True, verbose_name='Дата подачи')),
                ('done_flag', models.BooleanField(default=False, verbose_name='Отработано')),
                ('done_date', models.DateField(null=True, verbose_name='Дата выполнения')),
                ('subdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='anonym_form_app.subdivisionmodel', verbose_name='Ответственное подразделение')),
            ],
            options={
                'verbose_name': 'обращение',
                'verbose_name_plural': 'обращения',
            },
        ),
    ]
