# Generated by Django 5.1.1 on 2024-10-03 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonym_form_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subdivisionmodel',
            old_name='who_answer',
            new_name='subdivision_name',
        ),
        migrations.AddField(
            model_name='subdivisionmodel',
            name='subdivision_responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anonym_form_app.employeemodel', verbose_name='Кому присылать email'),
        ),
    ]
