# Generated by Django 5.1.1 on 2024-10-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonym_form_app', '0002_rename_who_answer_subdivisionmodel_subdivision_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Поступило'), (1, 'В работе'), (2, 'Выполнено')], default=0, verbose_name='Статус обращения'),
        ),
    ]
