# Generated by Django 5.1.1 on 2024-10-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonym_form_app', '0003_questionmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='start_work_date',
            field=models.DateField(null=True, verbose_name='Дата начала выполнения'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='done_date',
            field=models.DateField(null=True, verbose_name='Дата завершения'),
        ),
    ]
