# Generated by Django 5.1.1 on 2024-10-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonym_form_app', '0004_questionmodel_start_work_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='done_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='start_work_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала выполнения'),
        ),
    ]
