# Generated by Django 5.1.1 on 2024-10-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonym_form_app', '0006_qestionresultshowpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='description_canceled',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Отклонено'), (1, 'Актуально'), (2, 'В работе'), (3, 'Выполнено')], default=1, verbose_name='Статус обращения'),
        ),
    ]
