# Generated by Django 4.2.13 on 2024-10-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonym_form_app', '0007_questionmodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmodel',
            name='description_to_work',
            field=models.TextField(blank=True, null=True, verbose_name='Принятое решение'),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'Отклонено'), (1, 'Поступило'), (2, 'В работе'), (3, 'Выполнено')], default=1, verbose_name='Статус обращения'),
        ),
    ]
