# Generated by Django 4.2.13 on 2024-10-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonym_form_app', '0008_questionmodel_description_to_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='type_of_question',
            field=models.IntegerField(choices=[(1, 'Результат наблюдения за безопасностью и качеством'), (2, 'Предложение по развитию и совершенствованию')], default=2, verbose_name='Тип обращения'),
        ),
    ]
